
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@mui/material";
import Link from "next/link";
import MenuNav from "@/test/MenuNav";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ margin: 0, padding: 0 }}
      >
        <div style={{ display: 'flex', height: '100vh', width: '100vw' }}>
          <nav style={{ minWidth: 180, background: '#f5f5f5', padding: '30px 10px 10px 10px', display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '20px', boxShadow: '2px 0 8px #eee' }}>
            <Button color="primary" variant="contained" style={{ marginBottom: 30, width: '100%' }}>
              <Link href='/' style={{ color: 'inherit', textDecoration: 'none', width: '100%', display: 'block', textAlign: 'left' }}>Home</Link>
            </Button>
            <MenuNav />
          </nav>
          <main style={{ flex: 1, padding: '40px', overflow: 'auto' }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
